USE [master]
GO

/****** Object:  Database [BlowOutDB]    Script Date: 11/20/2019 2:01:43 PM ******/
CREATE DATABASE [BlowOutDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'New Database', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\New Database.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'New Database_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\New Database.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BlowOutDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BlowOutDB] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [BlowOutDB] SET ANSI_NULLS ON 
GO

ALTER DATABASE [BlowOutDB] SET ANSI_PADDING ON 
GO

ALTER DATABASE [BlowOutDB] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [BlowOutDB] SET ARITHABORT ON 
GO

ALTER DATABASE [BlowOutDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BlowOutDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BlowOutDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BlowOutDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BlowOutDB] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [BlowOutDB] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [BlowOutDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BlowOutDB] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [BlowOutDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BlowOutDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BlowOutDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BlowOutDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BlowOutDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BlowOutDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BlowOutDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BlowOutDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BlowOutDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BlowOutDB] SET RECOVERY FULL 
GO

ALTER DATABASE [BlowOutDB] SET  MULTI_USER 
GO

ALTER DATABASE [BlowOutDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BlowOutDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BlowOutDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BlowOutDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BlowOutDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BlowOutDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BlowOutDB] SET  READ_WRITE 
GO

